### ISSUE TITLE
Can't manage to add zigbee2mqqt converter for multisensor5

### ISSUE THREAD

**Issue by adminios** [rozenrod/multi_sensor_v1#3]
I've put multisensor_M5.js to data dir of zigbee2mqtt and add line to config. After restarting zigbee2mqtt I've got error:
```
Zigbee2MQTT:error 2021-10-13 20:55:06: Failed to call 'ExternalConverters' 'start' (AssertionError [ERR_ASSERTION]: Converter field exposes is undefined
    at validateDefinition (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/index.js:55:16)
    at Object.addDefinition [as addDeviceDefinition] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/index.js:86:5)
    at ExternalConverters.start (/opt/zigbee2mqtt/lib/extension/externalConverters.ts:12:17)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:427:81)
    at process._tickCallback (internal/process/next_tick.js:68:7))
```
Zigbee2MQTT version:
Zigbee2MQTT:info  2021-10-13 20:54:58: Starting Zigbee2MQTT version 1.21.2 (commit #44922120)
Zigbee2MQTT:info  2021-10-13 20:54:58: Starting zigbee-herdsman (0.13.149)

**Comment by rozenrod** [comment]
Рекомендую оформлять вашу прошивку в редакторе PTVO.  Он даст вам прошивку и файл для zigbee2mqtt
